// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublicTransportAPI.Data;

#nullable disable

namespace PublicTransportAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220417205622_InitMigration")]
    partial class InitMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.4");

            modelBuilder.Entity("PublicTransportAPI.Data.Models.Line", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LineIdentifier")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Lines");
                });

            modelBuilder.Entity("PublicTransportAPI.Data.Models.StopPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LineId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LineId");

                    b.ToTable("StopPoints");
                });

            modelBuilder.Entity("PublicTransportAPI.Data.Models.StopPoint", b =>
                {
                    b.HasOne("PublicTransportAPI.Data.Models.Line", null)
                        .WithMany("StopPoints")
                        .HasForeignKey("LineId");
                });

            modelBuilder.Entity("PublicTransportAPI.Data.Models.Line", b =>
                {
                    b.Navigation("StopPoints");
                });
#pragma warning restore 612, 618
        }
    }
}
